name: video_player
publish_to: "none"
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/plugins/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.2.18

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  video_player_android:
    git:
      url: https://github.com/navaronbracke/plugins.git
      ref: video_player_and_camera_hotfixes
      path: ./packages/video_player/video_player_android
  video_player_avfoundation:
    git:
      url: https://github.com/navaronbracke/plugins.git
      ref: video_player_and_camera_hotfixes
      path: ./packages/video_player/video_player_avfoundation
  video_player_platform_interface: 
    git:
      url: https://github.com/navaronbracke/plugins.git
      ref: video_player_and_camera_hotfixes
      path: ./packages/video_player/video_player_platform_interface
  video_player_web:
    git:
      url: https://github.com/navaronbracke/plugins.git
      ref: video_player_and_camera_hotfixes
      path: ./packages/video_player/video_player_web
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
